version: '3.8'

services:
  calendario:
    build:
      context: ./calendario
    container_name: calendario_app
    ports:
      - "8090:80"
    volumes:
      - ./calendario/data:/var/www/html/data
    restart: unless-stopped
    environment:
      - APP_ENV=dev
      - CALENDAR_DATA_DIR=/var/www/html/data
